import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Copy, Trash2, FileText, Calendar } from "lucide-react";
import { toast } from "sonner";

type Draft = {
  id: string;
  suggestion_id: string | null;
  reminder_id: string | null;
  kind: string;
  platform: string | null;
  title: string;
  body: string;
  hashtags: string[] | null;
  cta: string | null;
  status: string;
  created_at: string;
};

export default function AIDrafts() {
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [loading, setLoading] = useState(false);
  const [filter, setFilter] = useState<string>("all");

  async function load() {
    setLoading(true);
    const { data } = await supabase.from("ai_drafts").select("*").order("created_at", { ascending: false }).limit(100);
    setDrafts((data ?? []) as Draft[]);
    setLoading(false);
  }
  useEffect(() => { load(); }, []);

  async function copy(d: Draft) {
    const full = `${d.body}\n\n${(d.hashtags ?? []).join(" ")}\n${d.cta ?? ""}`.trim();
    await navigator.clipboard.writeText(full);
    toast.success("Caption copied to clipboard");
  }

  async function markPosted(d: Draft) {
    await supabase.from("ai_drafts").update({ status: "posted" }).eq("id", d.id);
    toast.success("Marked as posted");
    load();
  }

  async function discard(d: Draft) {
    if (!confirm("Delete this draft?")) return;
    if (d.reminder_id) await supabase.from("admin_reminders").delete().eq("id", d.reminder_id);
    await supabase.from("ai_drafts").delete().eq("id", d.id);
    toast.success("Deleted");
    load();
  }

  const filtered = filter === "all" ? drafts : drafts.filter((d) => d.platform === filter || d.status === filter);
  const platforms = ["all", "instagram", "tiktok", "twitter", "general", "posted"];

  return (
    <div className="space-y-6 max-w-4xl">
      <div>
        <h1 className="text-2xl font-display flex items-center gap-2"><FileText className="h-5 w-5 text-primary" /> AI Drafts</h1>
        <p className="text-sm text-muted-foreground">Social post drafts generated by Kicks from your marketing & content suggestions.</p>
      </div>

      <div className="flex gap-1 flex-wrap">
        {platforms.map((p) => (
          <Button key={p} variant={filter === p ? "default" : "outline"} size="sm" onClick={() => setFilter(p)}>{p}</Button>
        ))}
      </div>

      {loading && <p className="text-sm text-muted-foreground">Loading…</p>}
      {!loading && filtered.length === 0 && (
        <Card className="p-6 text-center text-sm text-muted-foreground">
          No drafts yet. Apply a marketing or content suggestion from the AI Suggestions inbox to generate one.
        </Card>
      )}
      {filtered.map((d) => (
        <Card key={d.id} className="p-4 space-y-3">
          <div className="flex items-center gap-2 flex-wrap">
            {d.platform && <Badge variant="outline">{d.platform}</Badge>}
            <Badge variant={d.status === "posted" ? "secondary" : "default"} className="text-[10px]">{d.status}</Badge>
            <span className="text-xs text-muted-foreground flex items-center gap-1"><Calendar className="h-3 w-3" /> {new Date(d.created_at).toLocaleString()}</span>
          </div>
          <p className="font-medium">{d.title}</p>
          <pre className="whitespace-pre-wrap text-sm bg-muted p-3 rounded font-sans">{d.body}</pre>
          {d.hashtags && d.hashtags.length > 0 && (
            <p className="text-xs text-primary">{d.hashtags.join(" ")}</p>
          )}
          {d.cta && <p className="text-xs text-muted-foreground italic">CTA: {d.cta}</p>}
          <div className="flex gap-2">
            <Button size="sm" onClick={() => copy(d)}><Copy className="h-3.5 w-3.5 mr-1" /> Copy caption</Button>
            {d.status !== "posted" && <Button size="sm" variant="outline" onClick={() => markPosted(d)}>Mark posted</Button>}
            <Button size="sm" variant="ghost" onClick={() => discard(d)}><Trash2 className="h-3.5 w-3.5" /></Button>
          </div>
        </Card>
      ))}
    </div>
  );
}